FROM node:latest as build
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build

FROM node:latest as deps
WORKDIR /app
COPY package*.json ./
RUN npm install --silent --production

FROM gcr.io/distroless/nodejs:latest
WORKDIR /app
COPY --from=build /app/dist .
COPY --from=deps /app .
COPY .env.example .

COPY .env .

CMD ["src/index.js"]