FROM node:latest
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json /app
RUN npm install --silent
ENV NODE_ENV=development \
  DATABASE_URL=postgresql://postgres:postgres@sitedata:5432/postgres \
  REDIS_URL=redis://redis:6379 \
  PORT=5000
CMD ["npm", "run", "server-dev"]