FROM node:latest as build

WORKDIR /app
RUN npm install -g typescript
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:latest as deps
WORKDIR /app
COPY package*.json ./
RUN npm install --silent --production

FROM node:slim
WORKDIR /app
COPY --from=build /app/dist .
COPY --from=deps /app .
ENV NODE_ENV=production