query Stonks(
  $take: Int!
  $skip: Int!
  $onlyPositions: Boolean!
  $order: String!
) {
  stonks(
    take: $take
    skip: $skip
    order: $order
    onlyPositions: $onlyPositions
  ) {
    items {
      ...stonk
    }
    hasMore
  }
}
