query Stonks($onlyPositions: Boolean, $order: String, $take: Int, $skip: Int) {
  stonks(
    take: $take
    skip: $skip
    order: $order
    onlyPositions: $onlyPositions
  ) {
    items {
      ...stonk
    }
    hasMore
  }
}
