fragment myMeme on Meme {
  id
  ups
  downs
  ratio
  createdAt
  title
  url
  numComments
  isHive
}

fragment meme on Meme {
  ...myMeme
  hasUpvoted
  hasDownvoted
}

fragment userMeme on Meme {
  ...meme
  user {
    ...user
  }
}
