mutation PostMeme($title: String!, $postToHive: Boolean!) {
  postMeme(title: $title, postToHive: $postToHive) {
    ...myMeme
  }
}
mutation DeleteMeme($memeId: String!) {
  deleteMeme(memeId: $memeId)
}
mutation SetMemeIsHive($memeId: String!) {
  setMemeIsHive(memeId: $memeId)
}
mutation GetSignedUrl($path: String!, $filename: String!) {
  getSignedUrl(path: $path, filename: $filename)
}

mutation UpVoteMeme($memeId: String!) {
  upVoteMeme(memeId: $memeId) {
    ...userMeme
  }
}
mutation DownVoteMeme($memeId: String!) {
  downVoteMeme(memeId: $memeId) {
    ...userMeme
  }
}
