query Comments($memeId: String!, $skip: Int!, $take: Int!, $order: String!) {
  comments(memeId: $memeId, skip: $skip, take: $take, order: $order) {
    items {
      ...userComment
    }
    hasMore
  }
}

query UserComments(
  $userId: String!
  $skip: Int!
  $take: Int!
  $order: String!
) {
  userComments(userId: $userId, skip: $skip, take: $take, order: $order) {
    items {
      ...comment
    }
    hasMore
  }
}

query MyComments($skip: Int!, $take: Int!, $order: String!) {
  myComments(skip: $skip, take: $take, order: $order) {
    items {
      ...myComment
    }
    hasMore
  }
}
