mutation PostComment($text: String!, $memeId: String!) {
  postComment(text: $text, memeId: $memeId) {
    ...myComment
  }
}

mutation SetCommentIsHive($commentId: String!, $permlink: String!) {
  setCommentIsHive(commentId: $commentId, permlink: $permlink)
}

mutation UpVoteComment($commentId: String!) {
  upVoteComment(commentId: $commentId) {
    ...userComment
  }
}
mutation DownVoteComment($commentId: String!) {
  downVoteComment(commentId: $commentId) {
    ...userComment
  }
}
