mutation PostComment($text: String!, $memeId: String!) {
  postComment(text: $text, memeId: $memeId)
}

mutation UpVoteComment($commentId: String!) {
  upVoteComment(commentId: $commentId) {
    ...userComment
  }
}
mutation DownVoteComment($commentId: String!) {
  downVoteComment(commentId: $commentId) {
    ...userComment
  }
}
