mutation Open($market: String!, $position: Int!, $entry: Int!) {
  open(market: $market, position: $position, entry: $entry) {
    id
  }
}
mutation Close($id: Int!, $exit: Int!) {
  close(id: $id, exit: $exit) {
    id
  }
}
