fragment user on User {
  id
  avatar
  username
  isHive
  mhp
  gbp
}

fragment stats on User {
  numMemeVotesGiven
  numMemeUpvotesRecieved
  numMemeDownvotesRecieved
  numMemeCommentsRecieved
  numCommentVotesGiven
  numCommentUpvotesRecieved
  numCommentDownvotesRecieved
}

fragment userProfile on User {
  ...user
  ...stats
}

fragment userResponse on UserResponse {
  errors {
    ...errors
  }
  user {
    ...user
  }
}
