fragment user on User {
  id
  avatar
  username
  isHive
  gbp
}

fragment userUpload on User {
  id
  username
  isHive
  lastHivePost
  lastMemehubPost
}

fragment userResponse on UserResponse {
  errors {
    ...errors
  }
  user {
    ...user
  }
}
