query Users {
  users {
    ...user
  }
}

query User($userId: String!) {
  user(userId: $userId) {
    ...user
  }
}

query Me {
  me {
    ...user
  }
}

query MeUpload {
  me {
    ...userUpload
  }
}

query IsHive {
  isHive
}
