mutation PostMeme(
  $title: String!
  $community: String!
  $clanId: Int
  $templateName: String
) {
  postMeme(
    title: $title
    community: $community
    clanId: $clanId
    templateName: $templateName
  ) {
    url
    id
  }
}
mutation GetSignedUrl($path: String!, $filename: String!) {
  getSignedUrl(path: $path, filename: $filename)
}

mutation UpVoteMeme($memeId: Int!) {
  upVoteMeme(memeId: $memeId) {
    ...userMeme
  }
}
mutation DownVoteMeme($memeId: Int!) {
  downVoteMeme(memeId: $memeId) {
    ...userMeme
  }
}
