query Meme($memeId: Int!) {
  meme(memeId: $memeId) {
    ...userMeme
  }
}
query MyMemes($take: Int!, $skip: Int!, $order: String!) {
  myMemes(take: $take, skip: $skip, order: $order) {
    items {
      ...myMeme
    }
    hasMore
  }
}
query UserMemes($userId: Int!, $take: Int!, $skip: Int!, $order: String!) {
  userMemes(userId: $userId, take: $take, skip: $skip, order: $order) {
    items {
      ...meme
    }
    hasMore
  }
}
query FollowingMemes($take: Int!, $skip: Int!, $order: String!) {
  followingMemes(take: $take, skip: $skip, order: $order) {
    items {
      ...userMeme
    }
    hasMore
  }
}
query NewMemes($take: Int!, $cursor: String) {
  newMemes(take: $take, cursor: $cursor) {
    items {
      ...userMeme
    }
    hasMore
  }
}
query HotMemes($take: Int!, $skip: Int) {
  hotMemes(take: $take, skip: $skip) {
    items {
      ...userMeme
    }
    hasMore
  }
}
query CommunityMemes($community: String!, $take: Int!, $skip: Int, $days: Int) {
  communityMemes(community: $community, take: $take, skip: $skip, days: $days) {
    items {
      ...userMeme
    }
    hasMore
  }
}
query TopRatedMemes($take: Int!, $skip: Int, $days: Int) {
  topRatedMemes(take: $take, skip: $skip, days: $days) {
    items {
      ...userMeme
    }
    hasMore
  }
}
